-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 15:28:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `idClasse` INT NOT NULL,
  `ClassName` VARCHAR(45) NULL,
  PRIMARY KEY (`idClasse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Presence` VARCHAR(45) BINARY NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `idSubject` INT NOT NULL AUTO_INCREMENT,
  `SubName` VARCHAR(45) NULL,
  PRIMARY KEY (`idSubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Class` (
  `User_idUser` INT NOT NULL,
  `Class_idClasse` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Class_idClasse`),
  INDEX `fk_User_has_Class_Class1_idx` (`Class_idClasse` ASC) VISIBLE,
  INDEX `fk_User_has_Class_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Class_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Class_Class1`
    FOREIGN KEY (`Class_idClasse`)
    REFERENCES `mydb`.`Class` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class_has_Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class_has_Subject` (
  `idCours` INT NOT NULL AUTO_INCREMENT,
  `Class_idClasse` INT NOT NULL,
  `Subject_idSubject` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Hr_Begin` TIME NULL,
  `Hr_End` TIME NULL,
  INDEX `fk_Class_has_Subject_Subject1_idx` (`Subject_idSubject` ASC) VISIBLE,
  INDEX `fk_Class_has_Subject_Class1_idx` (`Class_idClasse` ASC) VISIBLE,
  PRIMARY KEY (`idCours`, `Class_idClasse`, `Subject_idSubject`),
  CONSTRAINT `fk_Class_has_Subject_Class1`
    FOREIGN KEY (`Class_idClasse`)
    REFERENCES `mydb`.`Class` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_Subject_Subject1`
    FOREIGN KEY (`Subject_idSubject`)
    REFERENCES `mydb`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
